#
# nspark makefile (Windows NT, Microsoft V9.0 C Compiler)
#
# SYSTYPE:	WINNT
#
SYSTYPE= WINNT
INSTALLDIR= c:\msvc\bin
CC=	cl

# --- You shouldn't need to edit below this line ---

CDEFINES= -I. #-DDEBUGGING # -Ox -Gs
CMISC= -D$(SYSTYPE)
CFLAGS=	$(CDEFINES) $(CMISC) /O2
LDFLAGS= 
PROG=	nspark.exe
SRCS=	main.c arc.c unarc.c store.c pack.c compress.c crc.c \
	io.c error.c misc.c date.c arcfs.c garble.c
HDRS=	main.h arc.h unarc.h store.h pack.h compress.h crc.h \
	nsparkio.h error.h misc.h date.h os.h spark.h arcfs.h garble.h version.h
OBJS=	main.obj arc.obj unarc.obj store.obj pack.obj compress.obj crc.obj \
	io.obj error.obj misc.obj date.obj arcfs.obj winnt.obj garble.obj
LIBS=	

all:	$(PROG)

$(PROG): $(OBJS)
	$(CC) /Fe$(PROG) $(OBJS)

install: $(PROG)
	cp $(PROG) $(INSTALLDIR)

clean:
	rm $(PROG)
	rm *.obj 
	rm *.bak
	rm *.map
	rm mklog

# DO NOT DELETE THIS LINE -- make depend depends on it.

main.obj: spark.h nsparkio.h
main.obj: error.h misc.h arc.h unarc.h version.h
arc.obj: spark.h error.h
unarc.obj: spark.h store.h
unarc.obj: pack.h compress.h main.h nsparkio.h misc.h os.h error.h
store.obj: spark.h main.h crc.h nsparkio.h
pack.obj: spark.h main.h crc.h nsparkio.h
compress.obj: spark.h pack.h main.h crc.h nsparkio.h
crc.obj: spark.h main.h
io.obj: spark.h main.h nsparkio.h error.h arcfs.h
error.obj: error.h
misc.obj: spark.h main.h 
misc.obj: date.h misc.h
date.obj: spark.h
