#
# nspark makefile (Windows NT, Microsoft V9.0 C Compiler)
#
# SYSTYPE:	WINNT
#
SYSTYPE= WINNT
INSTALLDIR= c:\msvc
CC=	cl

# --- You shouldn't need to edit below this line ---

CDEFINES= -I. #-DDEBUGGING # -Ox -Gs
CMISC= -D$(SYSTYPE)
CFLAGS=	$(CDEFINES) $(CMISC) /O2
LIBS=
LDFLAGS= 
PROG=	nspark$(EXE)
SQSH=	sqsh$(EXE)
SRCS=	store.c pack.c compress.c crc.c \
	io.c error.c misc.c date.c arcfs.c garble.c
HDRS=	store.h pack.h compress.h crc.h \
	nsparkio.h error.h misc.h date.h os.h spark.h arcfs.h garble.h version.h
OBJS=	store$(OBJ) pack$(OBJ) compress$(OBJ) crc$(OBJ) \
	io$(OBJ) error$(OBJ) misc$(OBJ) date$(OBJ) arcfs$(OBJ) garble$(OBJ)

NSPARKSRCS = main.c arc.c unarc.c
NSPARKHDRS = main.h arc.h unarc.h
NSPARKOBJS = main$(OBJ) arc$(OBJ) unarc$(OBJ)

SQSHSRCS = sqshmain.c unarc.c
SQSHHDRS = unarc.h
SQSHOBJS = sqshmain$(OBJ) unarc$(OBJ)

EXE = .exe
OBJ = .obj
SRCS = $(SRCS) winnt.c
OBJS = $(OBJS) winnt$(OBJ)

all:	$(PROG) $(SQSH)

$(PROG): $(OBJS) $(NSPARKOBJS)
	$(CC) /Fe$(PROG) $(OBJS) $(NSPARKOBJS) $(LIBS)

$(SQSH): $(OBJS) $(SQSHOBJS)
	$(CC) /Fe$(SQSH) $(OBJS) $(SQSHOBJS) $(LIBS)

install: $(PROG) $(SQSH)
	-mkdir $(INSTALLDIR)\bin
	copy $(PROG) $(INSTALLDIR)\bin
	copy $(SQSH) $(INSTALLDIR)\bin

clean:
	rm *$(EXE)
	rm *$(OBJ)
	rm *.bak
	rm *.map
	rm mklog

# DO NOT DELETE THIS LINE -- make depend depends on it.

store$(OBJ): spark.h main.h crc.h garble.h
store$(OBJ): nsparkio.h
pack$(OBJ): spark.h main.h crc.h garble.h
pack$(OBJ): nsparkio.h pack.h
compress$(OBJ): spark.h pack.h
compress$(OBJ): main.h crc.h garble.h nsparkio.h arcfs.h
crc$(OBJ): spark.h main.h arcfs.h
io$(OBJ): spark.h main.h error.h arcfs.h nsparkio.h
error$(OBJ): error.h
misc$(OBJ): spark.h main.h date.h misc.h
date$(OBJ): spark.h
arcfs$(OBJ): spark.h arcfs.h nsparkio.h misc.h
garble$(OBJ): garble.h spark.h
main$(OBJ): spark.h nsparkio.h error.h misc.h arc.h unarc.h garble.h version.h
arc$(OBJ): spark.h error.h
unarc$(OBJ): spark.h store.h pack.h compress.h main.h nsparkio.h 
unarc$(OBJ): misc.h os.h error.h
unarc$(OBJ): crc.h arcfs.h
sqshmain$(OBJ): spark.h arcfs.h unarc.h
unarc$(OBJ): spark.h store.h pack.h compress.h main.h nsparkio.h 
unarc$(OBJ): misc.h os.h error.h
unarc$(OBJ): crc.h arcfs.h
testprog/pack$(OBJ): spark.h crc.h nsparkio.h pack.h arcfs.h garble.h spark.h
acorn$(OBJ): spark.h date.h
msdos$(OBJ): spark.h date.h 
msdos$(OBJ): os.h
winnt$(OBJ): spark.h date.h 
