#
# nspark makefile (Windows NT, Microsoft V9.0 C Compiler)
#
# SYSTYPE:	WINNT
#
SYSTYPE= WINNT
INSTALLDIR= c:\msvc\bin
CC=	cl

# --- You shouldn't need to edit below this line ---

CDEFINES= -I. #-DDEBUGGING # -Ox -Gs
CMISC= -D$(SYSTYPE)
CFLAGS=	$(CDEFINES) $(CMISC) /O2
LDFLAGS= 
PROG=	nspark$(EXE)
SRCS=	main.c arc.c unarc.c store.c pack.c compress.c crc.c \
	io.c error.c misc.c date.c arcfs.c garble.c
HDRS=	main.h arc.h unarc.h store.h pack.h compress.h crc.h \
	nsparkio.h error.h misc.h date.h os.h spark.h arcfs.h garble.h version.h
OBJS=	main$(OBJ) arc$(OBJ) unarc$(OBJ) store$(OBJ) pack$(OBJ) compress$(OBJ) crc$(OBJ) \
	io$(OBJ) error$(OBJ) misc$(OBJ) date$(OBJ) arcfs$(OBJ) winnt$(OBJ) garble$(OBJ)
LIBS=	

EXE = .exe
OBJ = .obj

all:	$(PROG)

$(PROG): $(OBJS)
	$(CC) /Fe$(PROG) $(OBJS)

install: $(PROG)
	cp $(PROG) $(INSTALLDIR)

clean:
	rm $(PROG)
	rm *$(OBJ)
	rm *.bak
	rm *.map
	rm mklog

# DO NOT DELETE THIS LINE -- make depend depends on it.

main$(OBJ): spark.h nsparkio.h error.h misc.h arc.h unarc.h garble.h version.h
arc$(OBJ): spark.h error.h
unarc$(OBJ): spark.h store.h pack.h compress.h main.h nsparkio.h misc.h os.h error.h crc.h arcfs.h
store$(OBJ): spark.h main.h crc.h garble.h nsparkio.h
pack$(OBJ): spark.h main.h crc.h garble.h nsparkio.h pack.h
compress$(OBJ): spark.h pack.h main.h crc.h garble.h nsparkio.h arcfs.h
arcfs$(OBJ): spark.h arcfs.h nsparkio.h misc.h
garble$(OBJ): garble.h
crc$(OBJ): spark.h main.h arcfs.h
io$(OBJ): spark.h main.h error.h arcfs.h nsparkio.h
error$(OBJ): error.h
misc$(OBJ): spark.h main.h date.h misc.h
date$(OBJ): spark.h
unix$(OBJ): spark.h date.h
acorn$(OBJ): spark.h date.h
msdos$(OBJ): spark.h date.h os.h
winnt$(OBJ): spark.h date.h
