on: [push, pull_request]

jobs:
  linuxbuild:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'ubuntu-20.04']
        cc: [ 'gcc', 'clang' ]
    name: Compile on ${{ matrix.os }} using ${{ matrix.cc }}
    env:
      CFLAGS: '-Wall -Wextra -Werror'
      CC: ${{ matrix.cc }}
    steps:
      - uses: actions/checkout@v2
      - run: mkdir build
      - run: cmake ..
        working-directory: ./build
      - run: cmake --build .
        working-directory: ./build

  analyzer:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-22.04']
        cc: [ 'gcc-12']
    name: Run static analyzer ${{ matrix.cc }}
    env:
      CFLAGS: '-Wall -Wextra -Werror -fanalyzer'
      CC: ${{ matrix.cc }}
    steps:
      - uses: actions/checkout@v2
      - run: mkdir build
      - run: cmake ..
        working-directory: ./build
      - run: cmake --build .
        working-directory: ./build
        continue-on-error: true
